backend:
  name: git-gateway
  branch: master

media_folder: content/images
public_folder: /images

collections:
  - name: "release"
    label: "Releases"
    label_singular: "Release"
    folder: "content/releases"
    create: true
    slug: "{{catalogNumber}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Catalog number", name: "catalogNumber", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Release date", name: "releaseDate", widget: "date", format: "YYYY-MM-DD" }
      - { label: "Cover image", name: "cover", widget: "file" }
      - { label: "Genres", name: "genre", widget: "list" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Bandcamp URL", name: "bandcampUrl", widget: "string" }
      - { label: "Spotify URL", name: "spotifyUrl", widget: "string", required: false }
    editor:
      preview: false
  - name: "article"
    label: "Articles"
    label_singular: "Article"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Release date", name: "releaseDate", widget: "date", format: "YYYY-MM-DD" }
      - { label: "Cover image", name: "cover", widget: "file" }
      - { label: "Lead", name: "lead", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
